# Generated by Django 5.2 on 2025-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loksabha", "0003_alter_loksabhaconstituency_unique_together_and_more"),
        ("maps", "0002_loksabhaconstituencymap"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="loksabhaconstituencymap",
            constraint=models.UniqueConstraint(
                fields=("LoksabhaConstituency",),
                name="unique_boundary_per_constituency",
            ),
        ),
    ]
