# Generated by Django 5.0 on 2024-05-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
        ('loksabha', '0001_initial'),
        ('n', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmsend', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='emailsendingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendto', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='excelupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelfileupload', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='assembly_constituency1',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts'),
        ),
        migrations.AddField(
            model_name='assembly_constituency1',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state'),
        ),
        migrations.AddField(
            model_name='assembly_constituency1',
            name='loksabhaconstituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loksabha.loksabha_constituency'),
        ),
        migrations.CreateModel(
            name='electionyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('resultdate', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('notification', models.FileField(null=True, upload_to='')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state')),
            ],
        ),
        migrations.CreateModel(
            name='Legislative_Assembly1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('MLA_name', models.CharField(default='', max_length=300)),
                ('presentorx', models.CharField(choices=[('present', 'present'), ('x', 'x')], default='present', max_length=500)),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=500)),
                ('District', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.districts')),
                ('Party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party1')),
                ('constituency_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assembly.assembly_constituency1')),
                ('state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['MLA_name'],
                'unique_together': {('MLA_name',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assembly_constituency1',
            unique_together={('Assembly_Constituency_Name',)},
        ),
        migrations.CreateModel(
            name='assemblyterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('date', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('mla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.legislative_assembly1')),
            ],
            options={
                'unique_together': {('mla', 'year', 'month', 'date')},
            },
        ),
        migrations.CreateModel(
            name='assemblypersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.legislative_assembly1')),
            ],
            options={
                'unique_together': {('mla',)},
            },
            bases=('n.personal',),
        ),
    ]
