# Generated by Django 5.0 on 2024-05-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('blue', 'blue')], default='blue', max_length=10)),
                ('activate', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('v', 'v'), ('p', 'p')], default='v', max_length=10)),
                ('Highlight', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
                ('url', models.CharField(max_length=50, null=True)),
                ('videourl', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('color', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.flag1')),
            ],
        ),
    ]
