# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='red', max_length=10)),
                ('activate', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('v', 'v'), ('p', 'p')], default='v', max_length=10)),
                ('Highlight', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=50, null=True)),
                ('path', models.CharField(max_length=50, null=True)),
            ],
            options={
                'unique_together': {('color',)},
            },
        ),
    ]
