# Generated by Django 3.2.10 on 2022-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('color',)},
            },
        ),
    ]
