# Generated by Django 3.2.10 on 2022-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='Status',
            field=models.CharField(choices=[('v', 'v'), ('p', 'p')], default='v', max_length=10),
        ),
    ]
