# Generated by Django 3.2.12 on 2022-02-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='path',
            new_name='name',
        ),
        migrations.AddField(
            model_name='flag',
            name='videourl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
