# Generated by Django 3.2.12 on 2022-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_auto_20220217_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('white', 'white'), ('blue', 'blue')], default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flag1',
            name='name',
            field=models.CharField(choices=[('red1', 'red1'), ('red2', 'red2'), ('red3', 'red3'), ('red4', 'red4'), ('red5', 'red5'), ('white1', 'white1'), ('white2', 'white2'), ('white3', 'white3'), ('white4', 'white4'), ('white5', 'white5'), ('blue1', 'blue1'), ('blue2', 'blue2'), ('blue3', 'blue3'), ('blue4', 'blue4'), ('blue5', 'blue5')], default='red1', max_length=10),
        ),
    ]
