# Generated by Django 3.2.10 on 2022-02-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_flag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='Highlight',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10),
        ),
    ]
