# Generated by Django 3.2.10 on 2022-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0003_flag_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
