# Generated by Django 3.2.12 on 2022-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_auto_20220218_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag1',
            name='name',
            field=models.CharField(choices=[('red', 'red'), ('white', 'white'), ('blue', 'blue')], default='blue', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flag',
            name='color',
        ),
    ]
