# Generated by Django 3.2.10 on 2022-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_auto_20220205_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='flag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
            ],
        ),
    ]
