# Generated by Django 3.2.12 on 2022-02-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0005_auto_20220220_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='color',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.flag1'),
        ),
    ]
