# Generated by Django 3.2.10 on 2022-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0005_flag1'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag1',
            name='name',
            field=models.CharField(default='red', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='flag1',
            unique_together={('name',)},
        ),
    ]
