# Generated by Django 5.2 on 2025-04-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0002_state_capital_alter_state_state_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="state",
            options={},
        ),
        migrations.RenameField(
            model_name="state",
            old_name="State_name",
            new_name="Statename",
        ),
    ]
