# Generated by Django 5.2 on 2025-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0003_alter_state_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="districts",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="districts",
            name="Districtname",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="districts",
            name="headquarters",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="Statename",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="capital",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
