# Generated by Django 5.2 on 2025-05-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0004_city_abbreviation_districts_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="districts",
            name="Revenuedivisons",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="districts",
            name="headquarters",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="districts",
            name="mandals",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Taluk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Talukname", models.CharField(max_length=50, unique=True)),
                (
                    "District",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="area_pop.districts",
                    ),
                ),
            ],
        ),
    ]
