# Generated by Django 5.2 on 2025-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0005_alter_districts_revenuedivisons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="districts",
            name="Districtname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="districts",
            unique_together={("State", "Districtname")},
        ),
    ]
