# Generated by Django 3.2.12 on 2022-05-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenuserprofile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='Education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='Mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='Spouse_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='Workingat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='fathers_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Mentioned', 'Not Mentioned')], default='Not Mentioned', max_length=15),
        ),
        migrations.AddField(
            model_name='citizenuserprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.msg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.msg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
