# Generated by Django 3.2.12 on 2022-05-10 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizen', '0003_alter_msg_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('happy', 'happy'), ('angry', 'angry'), ('sad', 'sad'), ('scared', 'scared'), ('proud', 'proud'), ('excited', 'excited'), ('disappointed', 'disappointed')], max_length=20)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.msg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
