# Generated by Django 3.2.12 on 2022-05-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_auto_20220510_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='feeling',
            field=models.CharField(choices=[('happy', 'happy'), ('angry', 'angry'), ('sad', 'sad'), ('scared', 'scared'), ('proud', 'proud'), ('excited', 'excited'), ('disappointed', 'disappointed')], max_length=20, null=True),
        ),
    ]
