# Generated by Django 3.2.12 on 2022-02-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipalcarporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('areainkm2', models.CharField(max_length=100, null=True)),
                ('formationyear', models.CharField(max_length=10, null=True)),
                ('lastelection', models.CharField(max_length=10, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state')),
            ],
        ),
    ]
