# Generated by Django 5.0 on 2024-06-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("n", "0001_initial"),
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="municipalcarporation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corporation_name", models.CharField(default="", max_length=100)),
                ("formationdate", models.CharField(default="", max_length=100)),
                ("population", models.CharField(default="", max_length=100)),
                ("lastelectionyear", models.CharField(default="", max_length=100)),
                ("areainkm2", models.CharField(default="", max_length=100)),
                (
                    "City",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="n.city",
                    ),
                ),
                (
                    "Districts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="n.districts",
                    ),
                ),
                (
                    "State",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="n.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mayor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(default="", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("fathers_Name", models.CharField(default="", max_length=100)),
                ("Spouse_Name", models.CharField(default="", max_length=100)),
                ("Highest_Education", models.CharField(default="", max_length=100)),
                ("University", models.CharField(default="", max_length=100)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photo/")),
                ("address", models.TextField(default="", max_length=600)),
                ("Email_address", models.EmailField(default="", max_length=100)),
                ("Mobile", models.CharField(default="", max_length=100)),
                ("chldid", models.CharField(default="no", max_length=100)),
                ("Mayor_Name", models.CharField(default="", max_length=100)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="party.party1",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carporations.municipalcarporation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="deputymayor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(default="", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("fathers_Name", models.CharField(default="", max_length=100)),
                ("Spouse_Name", models.CharField(default="", max_length=100)),
                ("Highest_Education", models.CharField(default="", max_length=100)),
                ("University", models.CharField(default="", max_length=100)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photo/")),
                ("address", models.TextField(default="", max_length=600)),
                ("Email_address", models.EmailField(default="", max_length=100)),
                ("Mobile", models.CharField(default="", max_length=100)),
                ("chldid", models.CharField(default="no", max_length=100)),
                ("DeputyMayor_Name", models.CharField(default="", max_length=100)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="party.party1",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carporations.municipalcarporation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="deputymayorpersonal1",
            fields=[
                (
                    "personal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="n.personal",
                    ),
                ),
                (
                    "deputymayor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carporations.deputymayor",
                    ),
                ),
            ],
            options={
                "unique_together": {("deputymayor",)},
            },
            bases=("n.personal",),
        ),
        migrations.CreateModel(
            name="mayorpersonal1",
            fields=[
                (
                    "personal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="n.personal",
                    ),
                ),
                (
                    "mayor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carporations.mayor",
                    ),
                ),
            ],
            options={
                "unique_together": {("mayor",)},
            },
            bases=("n.personal",),
        ),
    ]
