# Generated by Django 3.2.12 on 2022-02-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
        ('carporations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalcarporation',
            old_name='district',
            new_name='Districts',
        ),
        migrations.RenameField(
            model_name='municipalcarporation',
            old_name='state',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='municipalcarporation',
            name='formationyear',
        ),
        migrations.RemoveField(
            model_name='municipalcarporation',
            name='lastelection',
        ),
        migrations.RemoveField(
            model_name='municipalcarporation',
            name='name',
        ),
        migrations.AddField(
            model_name='municipalcarporation',
            name='City',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.city'),
        ),
        migrations.AddField(
            model_name='municipalcarporation',
            name='corporation_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipalcarporation',
            name='formationdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipalcarporation',
            name='lastelectionyear',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipalcarporation',
            name='population',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='municipalcarporation',
            name='areainkm2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
