# Generated by Django 3.2.12 on 2022-02-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
        ('party', '0001_initial'),
        ('carporations', '0002_auto_20220225_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='deputymayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('DeputyMayor_Name', models.CharField(default='', max_length=100)),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carporations.municipalcarporation')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('Mayor_Name', models.CharField(default='', max_length=100)),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carporations.municipalcarporation')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mayorpersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mayor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carporations.mayor')),
            ],
            options={
                'unique_together': {('mayor',)},
            },
            bases=('n.personal',),
        ),
        migrations.CreateModel(
            name='deputymayorpersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('deputymayor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carporations.deputymayor')),
            ],
            options={
                'unique_together': {('deputymayor',)},
            },
            bases=('n.personal',),
        ),
    ]
