# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_status', models.CharField(choices=[('Regional', 'regional'), ('National', 'national')], max_length=30)),
                ('partyname', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, null=True, unique=True)),
                ('President', models.CharField(max_length=100, null=True)),
                ('founder', models.CharField(max_length=100, null=True)),
                ('chairperson', models.CharField(max_length=100, null=True)),
                ('founded_date', models.DateField()),
                ('headquarters', models.CharField(max_length=1000)),
                ('seats_in_rajyasabha', models.IntegerField()),
                ('seats_in_loksabha', models.IntegerField()),
                ('party_symbol', models.ImageField(null=True, upload_to='Party/party_symbol/%Y-%m-%d/%H-%M-%S')),
                ('founderPhoto', models.ImageField(null=True, upload_to='Party/founderPhoto/%Y-%m-%d/%H-%M-%S')),
                ('chairpersonPhoto', models.ImageField(null=True, upload_to='Party/chairpersonPhoto/%Y-%m-%d/%H-%M-%S')),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='statepartyactivate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party1')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('party', 'state')},
            },
        ),
        migrations.CreateModel(
            name='districtpartyactivate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n.districts')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party1')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('party', 'district')},
            },
        ),
    ]
