# Generated by Django 3.2.10 on 2022-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_status', models.CharField(choices=[('Regional', 'regional'), ('National', 'national')], max_length=30)),
                ('partyname', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, null=True, unique=True)),
                ('President', models.CharField(max_length=100, null=True)),
                ('founder', models.CharField(max_length=100, null=True)),
                ('chairperson', models.CharField(max_length=100, null=True)),
                ('founded_date', models.DateField()),
                ('headquarters', models.CharField(max_length=1000)),
                ('seats_in_rajyasabha', models.IntegerField()),
                ('seats_in_loksabha', models.IntegerField()),
                ('party_symbol', models.ImageField(null=True, upload_to='Party/party_symbol/%Y-%m-%d/%H-%M-%S')),
                ('founderPhoto', models.ImageField(null=True, upload_to='Party/founderPhoto/%Y-%m-%d/%H-%M-%S')),
                ('chairpersonPhoto', models.ImageField(null=True, upload_to='Party/chairpersonPhoto/%Y-%m-%d/%H-%M-%S')),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=20)),
            ],
        ),
    ]
