# Generated by Django 3.2.10 on 2022-01-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0009_loksabha_complete_session'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statepartyactivate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party1')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('party', 'state')},
            },
        ),
        migrations.CreateModel(
            name='districtpartyactivate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n.districts')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party1')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('party', 'district')},
            },
        ),
    ]
