# Generated by Django 3.2.12 on 2022-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party1',
            name='headquarters',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
