# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rajyasabha1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('MP_name', models.CharField(default='', max_length=300)),
                ('elected', models.CharField(choices=[('Legislature', 'Legislature'), ('President', 'President')], default='Legislature', max_length=500)),
                ('presentorx', models.CharField(choices=[('present', 'present'), ('x', 'x')], default='present', max_length=500)),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=500)),
                ('Party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party1')),
                ('state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'ordering': ['MP_name'],
                'unique_together': {('MP_name',)},
            },
        ),
        migrations.CreateModel(
            name='Rajyasabhapresedential1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('MP_name', models.CharField(default='', max_length=300)),
                ('field', models.CharField(default='', max_length=300)),
                ('elected', models.CharField(choices=[('Legislature', 'Legislature'), ('President', 'President')], default='President', max_length=500)),
                ('presentorx', models.CharField(choices=[('present', 'present'), ('x', 'x')], default='present', max_length=500)),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=500)),
            ],
            options={
                'ordering': ['MP_name'],
                'unique_together': {('MP_name',)},
            },
        ),
        migrations.CreateModel(
            name='Rajyasabha_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=1000)),
                ('Rajyasabha_MP_Name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rajyasabha.rajyasabha1')),
                ('Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Rajyasabha_Complete_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('video_link', models.CharField(default='', max_length=1000)),
                ('Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Rajyasabhaterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('date', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('Rajyasabha_MP_Name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rajyasabha.rajyasabha1')),
            ],
            options={
                'unique_together': {('Rajyasabha_MP_Name', 'year', 'month', 'date')},
            },
        ),
        migrations.CreateModel(
            name='rajyasabhapersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rajyasabha.rajyasabha1')),
            ],
            options={
                'unique_together': {('mp',)},
            },
            bases=('n.personal',),
        ),
    ]
