[database]
user = "env:PROD_POSTGRES_USER"
password = "env:PROD_POSTGRES_PASSWORD"
host = "env:PROD_POSTGRES_HOST="
port = "env:PROD_POSTGRES_PORT"
name = "env:PROD_POSTGRES_DB"

[mega]
mega_email = "env:MEGA_EMAIL"
mega_password = "env:MEGA_PASSWORD"
db_backup_path = "/adhikar/politiaware/db_backups"
media_backup_path = "/adhikar/politiaware/media_backups"

[cloudinary]
cloud_name = "env:CLOUDINARY_CLOUD_NAME"
api_key = "env:CLOUDINARY_API_KEY"
api_secret = "env:CLOUDINARY_API_SECRET"
upload_folder = "media/uploads"        # optional: default folder for uploads
static_transform = "c_fill,w_500,h_500" # optional: default transformation string

[django-static]
# URL to access static files
static_url = "/static/"
# Path to collect static files
static_root = "staticfiles"

[django-media]
# URL to access media files
media_url = "/media/"
# Local path to store uploaded media files
media_root = "media"

