# Generated by Django 5.2 on 2025-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governor", "0004_remove_governor_age_remove_governor_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="governor",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hindu", "Hindu"),
                    ("Muslim", "Muslim"),
                    ("Sikh", "Sikh"),
                    ("Christian", "Christian"),
                    ("Buddhist", "Buddhist"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
