# Generated by Django 5.2 on 2025-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governor", "0005_alter_governor_religion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="governor",
            old_name="address",
            new_name="premanentaddress",
        ),
        migrations.AddField(
            model_name="governor",
            name="presentaddress",
            field=models.TextField(blank=True, default="", max_length=600, null=True),
        ),
    ]
