# Generated by Django 6.0 on 2026-01-15 13:33

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governor', '0006_rename_address_governor_premanentaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governor',
            name='voice_sample',
            field=models.FileField(blank=True, null=True, upload_to=person.models.upload_voice_sample),
        ),
    ]
