# Generated by Django 3.2.10 on 2022-01-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('n', '0008_delete_loksabha_complete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loksabha_Complete_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('video_link', models.CharField(default='', max_length=1000)),
                ('Loksabha_Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Loksabha_Session', to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
