# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokSabha1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('MP_name', models.CharField(max_length=300, null=True)),
                ('constituency_name', models.CharField(default='', max_length=200)),
                ('presentorx', models.CharField(choices=[('present', 'present'), ('x', 'x')], default='present', max_length=500)),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=500)),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts')),
            ],
            options={
                'ordering': ['MP_name'],
            },
        ),
        migrations.CreateModel(
            name='loksabhapersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.loksabha')),
            ],
            bases=('n.personal',),
        ),
        migrations.CreateModel(
            name='Loksabha_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=1000)),
                ('Loksabha_MP_Name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabha1')),
                ('Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Loksabha_Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loksabha_Constituency_Name', models.CharField(max_length=100)),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state')),
            ],
            options={
                'ordering': ['Loksabha_Constituency_Name'],
            },
        ),
        migrations.CreateModel(
            name='Loksabha_Complete_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('video_link', models.CharField(default='', max_length=1000)),
                ('Loksabha_Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
