# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('n', '0001_initial'),
        ('loksabha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loksabha1',
            name='Party',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party1'),
        ),
        migrations.AddField(
            model_name='loksabha1',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state'),
        ),
        migrations.AlterUniqueTogether(
            name='loksabhapersonal1',
            unique_together={('mp',)},
        ),
        migrations.AlterUniqueTogether(
            name='loksabha_constituency',
            unique_together={('Loksabha_Constituency_Name',)},
        ),
        migrations.AlterUniqueTogether(
            name='loksabha1',
            unique_together={('MP_name',)},
        ),
    ]
