# Generated by Django 3.2.10 on 2022-01-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loksabha_Complete_Session',
        ),
    ]
