# Generated by Django 5.0 on 2024-05-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loksabha', '0001_initial'),
        ('n', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loksabha1',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts'),
        ),
        migrations.AddField(
            model_name='loksabha1',
            name='Party',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party1'),
        ),
        migrations.AddField(
            model_name='loksabha1',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state'),
        ),
        migrations.AddField(
            model_name='loksabha_complete_session1',
            name='Loksabha_Session_Title',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions'),
        ),
        migrations.AddField(
            model_name='loksabha_constituency',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts'),
        ),
        migrations.AddField(
            model_name='loksabha_constituency',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state'),
        ),
        migrations.AddField(
            model_name='loksabha_session1',
            name='Loksabha_MP_Name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabha1'),
        ),
        migrations.AddField(
            model_name='loksabha_session1',
            name='Session_Title',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions'),
        ),
        migrations.AlterUniqueTogether(
            name='loksabha1',
            unique_together={('MP_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='loksabha_constituency',
            unique_together={('Loksabha_Constituency_Name',)},
        ),
        migrations.CreateModel(
            name='loksabhapersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.loksabha')),
            ],
            options={
                'unique_together': {('mp',)},
            },
            bases=('n.personal',),
        ),
    ]
