# Generated by Django 3.2.10 on 2022-01-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0009_loksabha_complete_session'),
        ('loksabha', '0003_loksabha1_loksabhapersonal1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loksabha_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=1000)),
                ('Loksabha_MP_Name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabha1')),
                ('Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Loksabha_Complete_Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('session', models.TextField(default='')),
                ('video_link', models.CharField(default='', max_length=1000)),
                ('Loksabha_Session_Title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.sessions')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
