# Generated by Django 5.2 on 2025-07-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loksabha", "0003_alter_loksabhaconstituency_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loksabhamp",
            name="Districts",
        ),
        migrations.RemoveField(
            model_name="loksabhamp",
            name="constituency_name",
        ),
    ]
