# Generated by Django 5.2 on 2025-04-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area_pop", "0003_alter_state_options_and_more"),
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cm_ruling_period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startdate", models.DateField(blank=True, null=True)),
                ("enddate", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="cm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("death_date", models.DateTimeField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                ("caste", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "caste_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OC", "OC"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fathers_Name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("fathers_image", models.TextField(blank=True, null=True)),
                (
                    "Spouse_Name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("spouse_image", models.TextField(blank=True, null=True)),
                (
                    "Highest_Education",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "University",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="person_photo/"),
                ),
                ("photo_path", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.TextField(blank=True, default="", max_length=600, null=True),
                ),
                (
                    "Email_address",
                    models.EmailField(
                        blank=True, default="", max_length=100, null=True
                    ),
                ),
                (
                    "Mobile",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("children", models.CharField(blank=True, max_length=100, null=True)),
                ("extra_info", models.TextField(blank=True, null=True)),
                (
                    "ispresent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "birth_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_city",
                        to="area_pop.city",
                    ),
                ),
                (
                    "birth_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_district",
                        to="area_pop.districts",
                    ),
                ),
                (
                    "birth_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_state",
                        to="area_pop.state",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cm_party",
                        to="party.party",
                    ),
                ),
                (
                    "rulingstate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cm_ruling_state",
                        to="area_pop.state",
                    ),
                ),
                (
                    "rulingperiods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cm.cm_ruling_period",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
