# Generated by Django 6.0 on 2026-01-15 13:33

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_rename_address_cm_premanentaddress_cm_presentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm',
            name='voice_sample',
            field=models.FileField(blank=True, null=True, upload_to=person.models.upload_voice_sample),
        ),
    ]
