# Generated by Django 5.2 on 2025-04-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="governor",
            old_name="is_present",
            new_name="ispresent",
        ),
        migrations.RenameField(
            model_name="governor",
            old_name="ruling_periods",
            new_name="rulingperiods",
        ),
        migrations.RenameField(
            model_name="governor",
            old_name="ruling_state",
            new_name="rulingstate",
        ),
        migrations.RenameField(
            model_name="governor_ruling_period",
            old_name="end_date",
            new_name="enddate",
        ),
        migrations.RenameField(
            model_name="governor_ruling_period",
            old_name="start_date",
            new_name="startdate",
        ),
    ]
