# Generated by Django 5.2 on 2025-05-22 17:28

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governor", "0003_alter_governor_religion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governor",
            name="age",
        ),
        migrations.RemoveField(
            model_name="governor",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="governor",
            name="photo_path",
        ),
        migrations.AddField(
            model_name="governor",
            name="person_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=person.models.upload_person_photo
            ),
        ),
        migrations.AlterField(
            model_name="governor",
            name="fathers_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=person.models.upload_father_photo
            ),
        ),
        migrations.AlterField(
            model_name="governor",
            name="spouse_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=person.models.upload_spouse_photo
            ),
        ),
    ]
