# Generated by Django 5.2 on 2025-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cm",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hindu", "Hindu"),
                    ("Muslim", "Muslim"),
                    ("Sikh", "Sikh"),
                    ("Christian", "Christian"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
