# Generated by Django 5.2 on 2025-07-11 03:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loksabha", "0002_alter_loksabhaconstituency_options_and_more"),
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoksabhaConstituencyMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "LoksabhaConstituency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loksabha.loksabhaconstituency",
                    ),
                ),
            ],
        ),
    ]
