# Generated by Django 6.1 on 2026-08-29 16:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_pop', '0008_state_unique_statename'),
        ('maps', '0003_loksabhaconstituencymap_unique_boundary_per_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area_pop.districts')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('District',), name='unique_boundary_per_district')],
            },
        ),
        migrations.CreateModel(
            name='StateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area_pop.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('State',), name='unique_boundary_per_state')],
            },
        ),
        migrations.CreateModel(
            name='TalukMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('Taluk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area_pop.taluk')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Taluk',), name='unique_boundary_per_taluk')],
            },
        ),
    ]
