# Generated by Django 5.2 on 2025-07-11 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loksabha", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loksabhaconstituency",
            options={},
        ),
        migrations.AlterModelOptions(
            name="loksabhamp",
            options={},
        ),
        migrations.RenameField(
            model_name="loksabhaconstituency",
            old_name="Districts",
            new_name="District",
        ),
        migrations.RemoveField(
            model_name="loksabhamp",
            name="state",
        ),
        migrations.AddField(
            model_name="loksabhamp",
            name="constituency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loksabha.loksabhaconstituency",
            ),
        ),
    ]
