# Generated by Django 5.2 on 2025-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0006_alter_districts_districtname_and_more"),
        ("loksabha", "0002_alter_loksabhaconstituency_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loksabhaconstituency",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="loksabhaconstituency",
            constraint=models.UniqueConstraint(
                fields=("State", "District", "LoksabhaConstituencyName"),
                name="unique_loksabhaconstituency",
            ),
        ),
    ]
