# Generated by Django 5.2 on 2025-07-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loksabha", "0004_remove_loksabhamp_districts_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loksabhamp",
            unique_together={("name",)},
        ),
        migrations.RemoveField(
            model_name="loksabhamp",
            name="MPName",
        ),
    ]
