# Generated by Django 6.0 on 2026-01-15 13:33

import django.db.models.deletion
import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0006_rename_address_loksabhamp_premanentaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loksabhamp',
            name='voice_sample',
            field=models.FileField(blank=True, null=True, upload_to=person.models.upload_voice_sample),
        ),
        migrations.CreateModel(
            name='VideoLoksabha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_sec', models.PositiveIntegerField()),
                ('end_time_sec', models.PositiveIntegerField()),
                ('other_mp', models.CharField(blank=True, help_text='Use when the MP is not in LokSabhaMP table', max_length=255, null=True)),
                ('mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabhamp')),
            ],
        ),
    ]
