# Generated by Django 6.0 on 2026-01-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0007_loksabhamp_voice_sample_videoloksabha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoLoksabha',
        ),
    ]
