# Generated by Django 3.0.5 on 2020-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bihar_Coalition_Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_status', models.CharField(choices=[('Regional', 'regional'), ('National', 'national')], max_length=30)),
                ('partyname', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, null=True)),
                ('President', models.CharField(max_length=100, null=True)),
                ('founder', models.CharField(max_length=100, null=True)),
                ('chairperson', models.CharField(max_length=100, null=True)),
                ('founded_date', models.DateField()),
                ('headquarters', models.CharField(max_length=1000)),
                ('seats_in_rajyasabha', models.IntegerField()),
                ('seats_in_loksabha', models.IntegerField()),
                ('party_symbol', models.ImageField(null=True, upload_to='photo/')),
                ('founderPhoto', models.ImageField(null=True, upload_to='photo/')),
                ('chairpersonPhoto', models.ImageField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Bihar_Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_status', models.CharField(choices=[('Regional', 'regional'), ('National', 'national')], max_length=30)),
                ('partyname', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, null=True)),
                ('President', models.CharField(max_length=100, null=True)),
                ('founder', models.CharField(max_length=100, null=True)),
                ('chairperson', models.CharField(max_length=100, null=True)),
                ('founded_date', models.DateField()),
                ('headquarters', models.CharField(max_length=1000)),
                ('seats_in_rajyasabha', models.IntegerField()),
                ('seats_in_loksabha', models.IntegerField()),
                ('party_symbol', models.ImageField(null=True, upload_to='photo/')),
                ('founderPhoto', models.ImageField(null=True, upload_to='photo/')),
                ('chairpersonPhoto', models.ImageField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='BiharCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiharRunners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100, unique='True')),
                ('total_contested', models.IntegerField()),
                ('no_of_votes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiharWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100, unique='True')),
                ('total_contested', models.IntegerField()),
                ('no_of_votes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DubbakaCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DubbakaRunners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100, unique='True')),
                ('total_contested', models.IntegerField()),
                ('no_of_votes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DubbakaWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya  Pradesh', 'Madhya  Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Candidate', models.CharField(default='', max_length=100)),
                ('District_name', models.CharField(default='', max_length=100)),
                ('Residence', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(default='', upload_to='photo/')),
                ('constituency_name', models.CharField(default='', max_length=100, unique='True')),
                ('total_contested', models.IntegerField()),
                ('no_of_votes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
