# Generated by Django 3.0.5 on 2020-11-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadingSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGB', models.IntegerField()),
                ('NDA', models.IntegerField()),
                ('LJP', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(default='', max_length=100, unique=True)),
                ('capital', models.CharField(default='', max_length=100, unique=True)),
                ('chief_minister', models.CharField(default='', max_length=100)),
                ('chief_minister_Photo', models.ImageField(null=True, upload_to='photo/')),
                ('Governor', models.CharField(default='', max_length=100)),
                ('Governor_Photo', models.ImageField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Bihar_Party',
            new_name='Party',
        ),
    ]
