# Generated by Django 3.0.5 on 2020-11-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bihar_Party',
            new_name='Party',
        ),
    ]
