# Generated by Django 3.2.12 on 2022-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='Revenuedivisons',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='areasqkm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='densitysqkm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='headquarters',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='mandals',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='population',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
