# Generated by Django 3.0.5 on 2020-11-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeadingSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGB', models.IntegerField()),
                ('NDA', models.IntegerField()),
                ('LJP', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bihar_Party',
            new_name='Party',
        ),
        migrations.RemoveField(
            model_name='biharcandidate',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='biharcandidate',
            name='Statename',
        ),
        migrations.RemoveField(
            model_name='biharrunners',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='biharrunners',
            name='Statename',
        ),
        migrations.RemoveField(
            model_name='biharwinners',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='biharwinners',
            name='Statename',
        ),
        migrations.RemoveField(
            model_name='dubbakacandidate',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='dubbakacandidate',
            name='Statename',
        ),
        migrations.RemoveField(
            model_name='dubbakarunners',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='dubbakarunners',
            name='Statename',
        ),
        migrations.RemoveField(
            model_name='dubbakawinners',
            name='District_name',
        ),
        migrations.RemoveField(
            model_name='dubbakawinners',
            name='Statename',
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(default='', max_length=100, unique=True)),
                ('chief_minister', models.CharField(default='', max_length=100)),
                ('chief_minister_Photo', models.ImageField(null=True, upload_to='photo/')),
                ('Governor', models.CharField(default='', max_length=100)),
                ('Governor_Photo', models.ImageField(null=True, upload_to='photo/')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
        ),
        migrations.CreateModel(
            name='Rajyasabha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathersName', models.CharField(default='', max_length=100)),
                ('SpouseName', models.CharField(default='', max_length=100)),
                ('HighestEducation', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('MPname', models.CharField(default='', max_length=300)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panchayat_Ward_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mandal', models.CharField(default='', max_length=100)),
                ('panchayat_name', models.CharField(default='', max_length=100)),
                ('Ward_Member_Name', models.CharField(default='', max_length=100)),
                ('Districts', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panchayat_time_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipal_corporation_time_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('corporation_name', models.CharField(default='', max_length=100)),
                ('City', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.City')),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LokSabha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathersName', models.CharField(default='', max_length=100)),
                ('SpouseName', models.CharField(default='', max_length=100)),
                ('HighestEducation', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('MPname', models.CharField(default='', max_length=300)),
                ('constituency_name', models.CharField(default='', max_length=200)),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legislative_Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathersName', models.CharField(default='', max_length=100)),
                ('SpouseName', models.CharField(default='', max_length=100)),
                ('HighestEducation', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('MLC_name', models.CharField(default='', max_length=300)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legislative_Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathersName', models.CharField(default='', max_length=100)),
                ('SpouseName', models.CharField(default='', max_length=100)),
                ('HighestEducation', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('address', models.TextField(default='', max_length=600)),
                ('MLA_name', models.CharField(default='', max_length=300)),
                ('constituency_name', models.CharField(default='', max_length=200)),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grama_panchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mandal', models.CharField(default='', max_length=100)),
                ('panchayat_name', models.CharField(default='', max_length=100)),
                ('Sarpanch_name', models.CharField(default='', max_length=100)),
                ('Districts', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='districts',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n.State'),
        ),
        migrations.CreateModel(
            name='Corporation_Ward_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ward_name', models.CharField(default='', max_length=100)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Corporator_name', models.CharField(default='', max_length=100)),
                ('City', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.City')),
                ('Districts', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Corporation_name', models.CharField(default='', max_length=100)),
                ('partyname', models.CharField(default='', max_length=100)),
                ('Mayor_name', models.CharField(default='', max_length=100)),
                ('City', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.City')),
                ('Districts', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.CreateModel(
            name='Assembly_time_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='biharcandidate',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='biharcandidate',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.AddField(
            model_name='biharrunners',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='biharrunners',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.AddField(
            model_name='biharwinners',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='biharwinners',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.AddField(
            model_name='dubbakacandidate',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='dubbakacandidate',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.AddField(
            model_name='dubbakarunners',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='dubbakarunners',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
        migrations.AddField(
            model_name='dubbakawinners',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts'),
        ),
        migrations.AddField(
            model_name='dubbakawinners',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State'),
        ),
    ]
