# Generated by Django 3.0.5 on 2020-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0002_auto_20201109_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadingSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGB', models.IntegerField()),
                ('NDA', models.IntegerField()),
                ('LJP', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
    ]
