# Generated by Django 3.0.5 on 2020-11-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0002_auto_20201130_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislative_council',
            name='presence',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
    ]
