# Generated by Django 3.2.12 on 2022-05-05 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('n', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofile',
            new_name='rolecheck',
        ),
    ]
