# Generated by Django 3.0.5 on 2020-11-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0003_legislative_council_presence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legislative_Council',
            new_name='Legislative_Council_Presence',
        ),
    ]
