# Generated by Django 3.2.12 on 2022-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0004_rename_userprofile_rolecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecheck',
            name='role',
            field=models.CharField(choices=[('citizen', 'citizen'), ('activist', 'activist'), ('adhikar', 'adhikar')], default='citizen', max_length=50),
        ),
    ]
