# Generated by Django 3.0.5 on 2020-11-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0004_auto_20201130_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='HighestEducation',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='MLC_name',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='SpouseName',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='University',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='address',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='fathersName',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='partyname',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='photo',
        ),
    ]
