# Generated by Django 3.2.14 on 2022-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0005_alter_rolecheck_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
