# Generated by Django 3.0.5 on 2020-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0005_auto_20201130_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_time_period',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assembly_time_period',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='corporation',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='corporation',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='corporation_ward_number',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grama_panchayat',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='municipal_corporation_time_period',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_time_period',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='HighestEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='SpouseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='address',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='fathersName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
