# Generated by Django 3.0.5 on 2020-11-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0007_auto_20201130_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='grama_panchayat',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='panchayat_ward_number',
            name='partyname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
