# Generated by Django 3.0.5 on 2020-11-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0008_auto_20201130_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='HighestEducation',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='SpouseName',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='University',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='address',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='fathersName',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='partyname',
        ),
        migrations.RemoveField(
            model_name='assembly_time_period',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='HighestEducation',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='SpouseName',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='University',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='address',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='fathersName',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='partyname',
        ),
        migrations.RemoveField(
            model_name='municipal_corporation_time_period',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='HighestEducation',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='SpouseName',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='University',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='address',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='fathersName',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='partyname',
        ),
        migrations.RemoveField(
            model_name='panchayat_time_period',
            name='photo',
        ),
    ]
