# Generated by Django 3.0.5 on 2020-11-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0009_auto_20201130_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grama_panchayat',
            name='partyname',
        ),
        migrations.RemoveField(
            model_name='panchayat_ward_number',
            name='partyname',
        ),
    ]
