# Generated by Django 3.0.5 on 2020-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0010_auto_20201130_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislative_council_presence',
            name='constituency_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='legislative_council_presence',
            name='elected_for_rajyasabha',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='governer', max_length=10),
        ),
        migrations.AddField(
            model_name='legislative_council_presence',
            name='total_member',
            field=models.IntegerField(null=True),
        ),
    ]
