# Generated by Django 3.0.5 on 2020-12-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0012_auto_20201201_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='constituency_name',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='elected_for_rajyasabha',
        ),
        migrations.RemoveField(
            model_name='legislative_council_presence',
            name='total_member',
        ),
        migrations.AddField(
            model_name='legislative_assembly',
            name='total_member',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loksabha',
            name='total_member',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rajyasabha',
            name='total_member',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Legislative_councils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elected_for_rajyasabha', models.CharField(choices=[('members of local body', 'members of local body'), ('members of legislative body', 'members of legislative body'), ('governer', 'governer'), ('graduates of three years', 'graduates of three years'), ('unniversity teacher of three years', 'unniversity teacher of three years')], default='governer', max_length=500)),
                ('MLA_name', models.CharField(default='', max_length=300)),
                ('constituency_name', models.CharField(default='', max_length=200)),
                ('total_member', models.IntegerField(null=True)),
                ('Districts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.Districts')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.State')),
            ],
        ),
    ]
