# Generated by Django 5.0 on 2024-05-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('n', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislative_councils1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('fathers_Name', models.CharField(default='', max_length=100)),
                ('Spouse_Name', models.CharField(default='', max_length=100)),
                ('Highest_Education', models.CharField(default='', max_length=100)),
                ('University', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=600)),
                ('Email_address', models.EmailField(default='', max_length=100)),
                ('Mobile', models.CharField(default='', max_length=100)),
                ('chldid', models.CharField(default='no', max_length=100)),
                ('elected', models.CharField(choices=[('Members of Local Body', 'Members of Local Body'), ('Members of legislative body', 'Members of Legislative Body'), ('Governor', 'Governor'), ('Graduates of three years', 'Graduates of three years'), ('University teacher of three years', 'University teacher of three years')], default='Governor', max_length=500)),
                ('MLC_name', models.CharField(default='', max_length=300)),
                ('Districts', models.CharField(default='', max_length=100)),
                ('constituency_name', models.CharField(default='', max_length=200)),
                ('presentorx', models.CharField(choices=[('present', 'present'), ('x', 'x')], default='present', max_length=500)),
                ('actvated', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('party', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party1')),
                ('state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state')),
            ],
            options={
                'unique_together': {('MLC_name',)},
            },
        ),
        migrations.CreateModel(
            name='councilterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('date', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state')),
                ('mlc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.legislative_councils1')),
            ],
            options={
                'unique_together': {('mlc', 'year', 'month', 'date')},
            },
        ),
        migrations.CreateModel(
            name='councilpersonal1',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='n.personal')),
                ('mlc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.legislative_councils1')),
            ],
            options={
                'unique_together': {('mlc',)},
            },
            bases=('n.personal',),
        ),
    ]
