# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('n', '0001_initial'),
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislative_councils1',
            name='party',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party1'),
        ),
        migrations.AddField(
            model_name='legislative_councils1',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state'),
        ),
        migrations.AddField(
            model_name='councilterm',
            name='mlc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.legislative_councils1'),
        ),
        migrations.AddField(
            model_name='councilpersonal1',
            name='mlc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.legislative_councils1'),
        ),
        migrations.AlterUniqueTogether(
            name='legislative_councils1',
            unique_together={('MLC_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='councilterm',
            unique_together={('mlc', 'year', 'month', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='councilpersonal1',
            unique_together={('mlc',)},
        ),
    ]
