# Generated by Django 3.2.12 on 2022-04-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0002_auto_20220418_0327'),
        ('council', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilterm',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state'),
        ),
    ]
