# Generated by Django 4.1.7 on 2023-03-16 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("n", "0006_alter_sessions_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minister",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1")], default="0", max_length=5
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("loksabha", "loksabha"),
                            ("rajyasabha", "rajyasabha"),
                        ],
                        default="loksabha",
                        max_length=15,
                    ),
                ),
                ("date", models.CharField(max_length=15, null=True)),
                ("time", models.CharField(max_length=15, null=True)),
                ("ministry", models.CharField(max_length=50, null=True)),
                ("videotime", models.CharField(max_length=15, null=True)),
                ("mpname", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("constituency", models.CharField(max_length=50, null=True)),
                ("party", models.CharField(max_length=50, null=True)),
                (
                    "image_data",
                    models.TextField(
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_base64_image",
                                message="Invalid base64 encoded image format",
                                regex="^data:image\\/\\w+;base64,",
                            )
                        ]
                    ),
                ),
                (
                    "Session_Title",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="n.sessions",
                    ),
                ),
            ],
        ),
    ]
