# Generated by Django 5.0 on 2025-04-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("State_name", models.CharField(max_length=1000, unique=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[("State", "State"), ("UT", "UT")],
                        default="State",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["State_name"],
            },
        ),
        migrations.CreateModel(
            name="area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formationdate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("areasqkm", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "densitysqkm",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="population",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totalpopulation",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "malepopulation",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "femalepopulation",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "census_year",
                    models.IntegerField(choices=[(2011, "2011")], default=2011),
                ),
                (
                    "DecadalGrowthRate",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "LiteracyRate",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("femtomaleSexRatio", models.CharField(max_length=100, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Districtname", models.CharField(max_length=100, unique=True)),
                ("headquarters", models.CharField(max_length=100, null=True)),
                ("Revenuedivisons", models.CharField(max_length=100, null=True)),
                ("mandals", models.CharField(max_length=100, null=True)),
                (
                    "State",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="District",
                        to="area_pop.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cityname", models.CharField(max_length=100, unique=True)),
                (
                    "Districts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="area_pop.districts",
                    ),
                ),
                (
                    "State",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="area_pop.state",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="unique_area_per_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="population",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "census_year"),
                name="unique_entity_census_year",
            ),
        ),
    ]
