# Generated by Django 5.2 on 2025-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="capital",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="state",
            name="State_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="Status",
            field=models.CharField(
                choices=[("State", "State"), ("UT", "UT")],
                default="State",
                max_length=6,
            ),
        ),
    ]
