# Generated by Django 5.2 on 2025-07-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0006_alter_districts_districtname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="oldname",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
