# Generated by Django 5.2 on 2025-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0007_state_oldname"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("Statename",), name="unique_Statename"
            ),
        ),
    ]
