# Generated by Django 5.0 on 2024-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly_Constituency1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assembly_Constituency_Name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Assembly_Constituency_Name'],
            },
        ),
    ]
