# Generated by Django 3.2.12 on 2022-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('n', '0001_initial'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislative_assembly1',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party1'),
        ),
        migrations.AddField(
            model_name='legislative_assembly1',
            name='constituency_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assembly.assembly_constituency1'),
        ),
        migrations.AddField(
            model_name='legislative_assembly1',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='n.state'),
        ),
        migrations.AddField(
            model_name='assemblyterm',
            name='mla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.legislative_assembly1'),
        ),
        migrations.AddField(
            model_name='assemblypersonal1',
            name='mla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.legislative_assembly1'),
        ),
        migrations.AddField(
            model_name='assembly_constituency1',
            name='Districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.districts'),
        ),
        migrations.AddField(
            model_name='assembly_constituency1',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='n.state'),
        ),
        migrations.AlterUniqueTogether(
            name='legislative_assembly1',
            unique_together={('MLA_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='assemblyterm',
            unique_together={('mla', 'year', 'month', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='assemblypersonal1',
            unique_together={('mla',)},
        ),
        migrations.AlterUniqueTogether(
            name='assembly_constituency1',
            unique_together={('Assembly_Constituency_Name',)},
        ),
    ]
