# Generated by Django 3.2.12 on 2022-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='excelupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelfileupload', models.FileField(upload_to='excel')),
            ],
        ),
    ]
