# Generated by Django 3.2.12 on 2022-04-18 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0002_initial'),
        ('assembly', '0004_alter_excelupload_excelfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_constituency1',
            name='loksabhaconstituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loksabha.loksabha_constituency'),
        ),
    ]
