# Generated by Django 3.2.12 on 2022-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_assembly_constituency1_loksabhaconstituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmsend', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10)),
            ],
        ),
    ]
