# Generated by Django 3.2.12 on 2022-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_emailsend'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsendingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('process', 'process')], default='no', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
