# Generated by Django 3.2.12 on 2022-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_emailsendingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsendingstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='emailsendingstatus',
            name='sendto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
