# Generated by Django 3.2.12 on 2022-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_electionyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionyear',
            old_name='date',
            new_name='resultdate',
        ),
        migrations.AddField(
            model_name='electionyear',
            name='notification',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
